site_name: Maxonrow Blockchain <br /> v1.0
nav:
    - Home: index.md
    - Node CLI: mxw-Node-CLI.md
    - Node RPC: mxw-Node-RPC.md
    - API Reference SDK: mxw-SDKs.md
    - FAQ: mxw-FAQ.md
    - Wallets: mxw-Wallets.md
    - Tutorials: mxw-Tutorials.md
    - More Help: mxw-More-help.md
    - Maxonrow RPC client Testnet: https://alloys-rpc.maxonrow.com "Maxonrow RPC client Testnet" 
    - Blockchain Explorer Testnet: https://max-scan.usdp.io/ "Blockchain Explorer Testnet" 
theme: readthedocs
use_directory_urls: false